#!/usr/bin/env python3
"""Recompute PPM birefringence images in a folder with the current per-channel method.

Walks a folder recursively, finds birefringence images (filename contains "biref"),
locates each one's positive/negative angle source tiles, and recomputes the biref
using the current ``ppm_library.imaging.writer.TifWriterUtils.ppm_normalized_difference_abs``
(per-channel color-RMS). Importing the library function guarantees the output matches
what fresh acquisitions now produce.

Source-file convention (matches the acquisition writer):

    <base>_<angle>_biref<tail>.ome.tif    biref (angle = the POSITIVE angle)
    <base>_<angle><tail>.ome.tif          I(+) positive-angle source
    <base>_-<angle><tail>.ome.tif         I(-) negative-angle source

Recomputation is ONLY possible while the two angle source tiles still exist. Once the
originals are gone (they can be hundreds of GB, so they are often deleted after
stitching) the biref cannot be regenerated -- such files are reported as skipped. This
works on full stitched slides just as well as on per-tile files: the two angle images
are read at full resolution and the biref is rewritten.

Output format matches the production stitched biref (QPSC ``DirectTiffOutputWriter``):
a pyramidal OME-TIFF, single-channel uint16 (minisblack, big-endian), 512-pixel tiles,
LZW compression, factor-2 pyramid levels down to the tile size, BigTIFF when large,
physical pixel size carried over from the source. Downsampled levels are generated by
strip-wise 2x2 area averaging (repeated halving equals a full-block average, so each
level matches downsampling from full resolution) -- no full-image resize, so arbitrarily
large slides are handled. The full-resolution biref is held in RAM when it fits within
``--mem-budget-gb``, otherwise in a temporary memory-mapped file beside the output.

Usage:
    ppm-recompute-biref FOLDER [--suffix _colorrms] [--overwrite] [--dry-run]
        [--min-intensity 0] [--strip 2048] [--tile 512] [--compression lzw]
        [--mem-budget-gb 3]
"""

import argparse
import contextlib
import re
import sys
from pathlib import Path

import numpy as np
import tifffile as tf

from ppm_library.imaging.writer import TifWriterUtils

# Positive angle sits immediately before "_biref"; tail is whatever follows (e.g. _001).
_BIREF_RE = re.compile(r"^(?P<head>.*_)(?P<angle>-?\d+(?:\.\d+)?)_biref(?P<tail>.*)$")
_EXTS = (".ome.tif", ".ome.tiff", ".tif", ".tiff")

# Output tuning that mirrors the production stitched-biref writer
# (qupath-extension-tiles-to-pyramid DirectTiffOutputWriter): 512-pixel tiles, factor-2
# pyramid stopping below the tile size, LZW by default (QPSC picks LZW over J2K because
# J2K corrupts lower pyramid levels in Bio-Formats). Big-endian uint16 minisblack.
_MAX_PYRAMID_LEVELS = 16
# Classic TIFF tops out near 4 GB of offsets; switch to BigTIFF with the same ~2 GB
# safety margin the Java writer uses.
_BIGTIFF_THRESHOLD_BYTES = 2**31 - 100 * 1024**2
# tifffile/imagecodecs compression names; None means uncompressed.
_COMPRESSION = {"lzw": "lzw", "zlib": "zlib", "jpeg2000": "jpeg2000", "none": None}


def _split_ext(name):
    for ext in _EXTS:
        if name.lower().endswith(ext):
            return name[: -len(ext)], name[-len(ext) :]
    return None, None


def sources_for(biref_path: Path):
    """Return (pos_path, neg_path) source candidates for a biref file, or (None, None)."""
    stem, suffix = _split_ext(biref_path.name)
    if stem is None:
        return None, None
    m = _BIREF_RE.match(stem)
    if not m:
        return None, None
    head, angle, tail = m.group("head"), m.group("angle"), m.group("tail")
    neg_angle = angle[1:] if angle.startswith("-") else "-" + angle
    pos_name = f"{head}{angle}{tail}{suffix}"
    neg_name = f"{head}{neg_angle}{tail}{suffix}"
    return biref_path.with_name(pos_name), biref_path.with_name(neg_name)


def output_path(biref_path: Path, suffix: str, overwrite: bool):
    if overwrite:
        return biref_path
    stem, ext = _split_ext(biref_path.name)
    return biref_path.with_name(f"{stem}{suffix}{ext}")


def _read_strip(path, y0, y1, level=0):
    import zarr

    store = tf.imread(str(path), aszarr=True, level=level)
    z = zarr.open(store, mode="r")
    a = np.asarray(z[y0:y1])
    store.close()
    return a.astype(np.float32)[..., :3]


def _pixel_size_um(path):
    try:
        with tf.TiffFile(str(path)) as t:
            om = t.ome_metadata or ""
        m = re.search(r'PhysicalSizeX="([0-9.]+)"', om)
        return float(m.group(1)) if m else None
    except Exception:
        return None


def pyramid_downsamples(width, height, tile):
    """Factor-2 pyramid downsamples [1, 2, 4, ...].

    Halves each level and stops once the next level would be smaller than the tile size
    in either dimension (capped at 16 levels). Matches
    ``DirectTiffOutputWriter.computePyramidDownsamples`` so the recomputed pyramid has
    the same level structure as production output.
    """
    levels = [1]
    d = 1
    while len(levels) < _MAX_PYRAMID_LEVELS:
        nxt = d * 2
        if (width // nxt) < tile or (height // nxt) < tile:
            break
        levels.append(nxt)
        d = nxt
    return levels


def downsample_half(src, strip):
    """2x2 area-average downsample of a (H, W) uint16 array, returned as uint16.

    Processed in row-strips so the float32 working buffer stays bounded regardless of
    image size (``src`` may be an ndarray or a numpy memmap). Repeated halving equals a
    full 2^k x 2^k block average, so iterating this to build each pyramid level matches
    downsampling that level directly from full resolution.
    """
    h, w = src.shape
    h2, w2 = h // 2, w // 2
    out = np.empty((h2, w2), np.uint16)
    for oy0 in range(0, h2, strip):
        oy1 = min(oy0 + strip, h2)
        block = src[2 * oy0 : 2 * oy1, : 2 * w2].astype(np.float32)
        block = block.reshape(oy1 - oy0, 2, w2, 2).mean(axis=(1, 3))
        out[oy0:oy1] = np.clip(block + 0.5, 0, 65535).astype(np.uint16)
    return out


def _write_pyramid(base, out_path, px, tile, compression, strip):
    """Write ``base`` (full-res uint16 biref) as a pyramidal OME-TIFF matching production."""
    h, w = base.shape
    downs = pyramid_downsamples(w, h, tile)
    metadata = {"axes": "YX"}
    if px:
        metadata.update(
            {
                "PhysicalSizeX": px,
                "PhysicalSizeY": px,
                "PhysicalSizeXUnit": "um",
                "PhysicalSizeYUnit": "um",
            }
        )
    opts = {"tile": (tile, tile), "photometric": "minisblack"}
    if compression is not None:
        opts["compression"] = compression

    total_bytes = sum((w // d) * (h // d) * 2 for d in downs)
    bigtiff = total_bytes >= _BIGTIFF_THRESHOLD_BYTES

    # Big-endian to match the production writer (Bio-Formats packs 16-bit samples BE).
    with tf.TiffWriter(str(out_path), bigtiff=bigtiff, byteorder=">", ome=True) as tif:
        tif.write(base, subifds=len(downs) - 1, metadata=metadata, **opts)
        prev = base
        for _ in downs[1:]:
            level = downsample_half(prev, strip)
            tif.write(level, subfiletype=1, **opts)
            prev = level


def recompute_one(pos_path, neg_path, out_path, min_intensity, strip, tile, compression, mem_bytes):
    with tf.TiffFile(str(pos_path)) as t:
        h, w = t.series[0].levels[0].shape[:2]
    px = _pixel_size_um(pos_path)

    def biref_strip(y0, y1):
        p = _read_strip(pos_path, y0, y1)
        n = _read_strip(neg_path, y0, y1)
        return TifWriterUtils.ppm_normalized_difference_abs(p, n, min_intensity=min_intensity)

    # Hold the full-res biref in RAM when it fits the budget, else in a temp memmap so
    # the tile-by-tile pyramid write can stream from it regardless of image size.
    base_bytes = h * w * 2
    tmp = None
    if base_bytes <= mem_bytes:
        base = np.zeros((h, w), np.uint16)
    else:
        tmp = out_path.with_name(out_path.name + ".basetmp.dat")
        base = np.memmap(str(tmp), dtype=np.uint16, mode="w+", shape=(h, w))

    try:
        for y0 in range(0, h, strip):
            y1 = min(y0 + strip, h)
            base[y0:y1] = biref_strip(y0, y1)
        if tmp is not None:
            base.flush()
        _write_pyramid(base, out_path, px, tile, compression, strip)
    finally:
        if tmp is not None:
            del base
            with contextlib.suppress(OSError):
                tmp.unlink()
    return h, w


def main(argv=None):
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("folder", help="folder to scan recursively for biref images")
    ap.add_argument(
        "--suffix", default="_colorrms", help="suffix for recomputed output (default _colorrms)"
    )
    ap.add_argument(
        "--overwrite", action="store_true", help="overwrite the original biref in place"
    )
    ap.add_argument(
        "--dry-run", action="store_true", help="report what would happen, write nothing"
    )
    ap.add_argument(
        "--min-intensity", type=float, default=0.0, help="dark-region mask threshold (8-bit scale)"
    )
    ap.add_argument("--strip", type=int, default=2048, help="row-strip height for streaming")
    ap.add_argument(
        "--tile", type=int, default=512, help="output tile size (default 512, matches QPSC)"
    )
    ap.add_argument(
        "--compression",
        default="lzw",
        choices=sorted(_COMPRESSION),
        help="output compression (default lzw, matches the QPSC stitched biref)",
    )
    ap.add_argument(
        "--mem-budget-gb",
        type=float,
        default=3.0,
        help="hold the full-res biref in RAM up to this size, else use a temp memmap",
    )
    ap.add_argument(
        "--force", action="store_true", help="recompute even if the output already exists"
    )
    args = ap.parse_args(argv)

    root = Path(args.folder)
    if not root.is_dir():
        print(f"ERROR: not a folder: {root}", file=sys.stderr)
        return 2

    compression = _COMPRESSION[args.compression]
    mem = int(args.mem_budget_gb * 1024**3)
    done = missing = skipped = failed = 0
    for path in sorted(root.rglob("*")):
        if not path.is_file():
            continue
        low = path.name.lower()
        if "biref" not in low or not low.endswith(_EXTS):
            continue
        # Don't reprocess our own outputs.
        if args.suffix and args.suffix.lower() in low:
            continue

        pos, neg = sources_for(path)
        if pos is None:
            print(f"[skip  ] {path.name}: unrecognized biref name pattern")
            skipped += 1
            continue
        if not (pos.exists() and neg.exists()):
            miss = [str(p.name) for p in (pos, neg) if not p.exists()]
            print(
                f"[MISSING] {path.name}: source tiles gone ({', '.join(miss)}) -- cannot recompute"
            )
            missing += 1
            continue

        out = output_path(path, args.suffix, args.overwrite)
        if out.exists() and not (args.overwrite or args.force):
            print(f"[exists] {out.name}: already present (use --force to redo)")
            skipped += 1
            continue

        if args.dry_run:
            print(f"[dry   ] {path.name} -> {out.name}  (pos={pos.name}, neg={neg.name})")
            done += 1
            continue

        try:
            h, w = recompute_one(
                pos, neg, out, args.min_intensity, args.strip, args.tile, compression, mem
            )
            print(f"[ok    ] {out.name}  ({w}x{h})")
            done += 1
        except Exception as e:  # noqa: BLE001 - report and continue the batch
            print(f"[FAIL  ] {path.name}: {e}")
            failed += 1

    print(
        f"\nsummary: {done} recomputed, {missing} un-recomputable (sources gone), "
        f"{skipped} skipped, {failed} failed"
    )
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
